version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-mem-ledger
    ports:
      - "50051:50051"
    volumes:
      - .:/app
    environment:
      - MYSQL_DSN=user:password@tcp(mysql:3306)/ledger_db?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      - mysql
    command: ["go", "run", "cmd/core/main.go"] # 開發模式直接 run

  mysql:
    image: mysql:8.0
    container_name: ledger-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ledger_db
      TZ: Asia/Taipei
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d # 初始化 SQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ledger-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      TZ: Asia/Taipei
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
